### ISSUE TITLE
(feature) Tab Completion

### ISSUE THREAD

**Issue by lucymhdavies** [borksh/bork#19]
```
bork <TAB>
```

Would be useful if it could then display all the subcommands.

**Comment by skylarmacdonald** [comment]
This is turning out to be both easy and difficult!

It would be pretty straightforward to do this for just the subcommands, but to be smarter than that (which would be ideal) would take more work, that I am slowly figuring out how to do…

There's also the difficulty that the macOS default shell is zsh these days, so we would ideally ship completions for both bash and zsh. (I don't understand fish enough, so the fish users can submit their own PR. 😉)

But I am determined to do this for 0.14.x!
