### ISSUE TITLE
(bug) (types) Skip `mas account` for the short term

### ISSUE THREAD

**Issue by lucymhdavies** [borksh/bork#42]
As a workaround for https://github.com/mas-cli/mas/issues/417

https://github.com/borksh/bork/blob/f7fdc7603e70731eecfa6391fba6251a38ef28e0/types/mas.sh#L17-L18

We could check if the version of macOS >= 12, and skip the `mas account` step.

The consequences of this would be that, if a user is not logged in to the App Store, bork could erroneously report STATUS_MISSING. But until the mas-cli issue above is fixed, this may be an okay compromise.
It does however set a precedent for adding workarounds to bugs in dependencies.

Oh great leader @skylarmacdonald , how would you like to approach this one?

**Comment by skylarmacdonald** [comment]
I don't necessarily see anything wrong with working around a bug in an upstream dependency ourselves. This looks like it's going to be a thorny issue to fix and will probably trip up a handful of people.

I reckon we do as you suggest. I would be in favour of still running `bake mas account`, just in case it magically starts to work again, but only then returning `$STATUS_FAILED_PRECONDITION` if we are on a version of macOS where that command works. Something like this (pseudocode):

```bash
bake mas account
[ "$?" -gt 0 ] && [ "$macos" -lt "12" ] && return $STATUS_FAILED_PRECONDITION
```

(Obviously, the `$macos` variable there is made up, but if we can figure out a way to do that check then that's how I would tackle it.)

**Comment by lucymhdavies** [comment]
So the annoying thing is we'd not actually be checking against "12"

Because the operating system branded as macOS 12, is actually... Darwin 21 😂 
https://en.wikipedia.org/wiki/Darwin_(operating_system)

I'm on 12.3, and...

```
$ uname -r
21.4.0
```

But the concept holds.

And I do like your version better, where it's future-compatible with when the mas-cli devs are able to fix that bug.

**Comment by lucymhdavies** [comment]
here:
https://github.com/borksh/bork/blob/main/lib/helpers/system.sh#L39-L50

Something like...

```
get_baking_platform_release() {
  bake uname -r
}
```

**Comment by skylarmacdonald** [comment]
That's not a bad approach. `baking_platform` is for future-proofing — the "baking platform" is the target system, whereas the `platform` is the source system on which you are running your script. Right now these are one and the same, but they might not be some day. So in this case, you should check what the _baking_ platform's release is, as that's where you will be running `mas`.

**Comment by lucymhdavies** [comment]
```
        [ "$?" -gt 0 ] && [[ get_baking_platform_release < "21" ]] && return $STATUS_FAILED_PRECONDITION
```

```
✔ strawb@HashiBook ~/git_src/github.com/borksh/bork/lib/helpers [main|✚ 2]
$ bork check ok mas 441258766 Magnet
Error: This command is not supported on this macOS version due to changes in macOS. For more information see: https://github.com/mas-cli/mas#known-issues
error (failed precondition): mas 441258766 Magnet

✘-33 strawb@HashiBook ~/git_src/github.com/borksh/bork/lib/helpers [main|✚ 2]
$ ~/git_src/github.com/borksh/bork/bin/bork check ok mas 441258766 Magnet
Error: This command is not supported on this macOS version due to changes in macOS. For more information see: https://github.com/mas-cli/mas#known-issues
ok: mas 441258766 Magnet
```
