### ISSUE TITLE
New bork release?

### ISSUE THREAD

**Issue by lucymhdavies** [borksh/bork#47]
We've not had a new release in a while. There's a few things listed in the 0.14.x milestone still to do, but there's quite a bit of new stuff we've added since 0.13.

Are you up for cutting an 0.14.0 to release those, and pushing the rest back to 0.15.x (or v1.0)?

Semi-related, it looks like installing bork with `--HEAD` isn't currently working 🤔 

```
$ brew install bork --HEAD --fetch-HEAD
==> Cloning https://github.com/borksh/bork.git
Updating /Users/strawb/Library/Caches/Homebrew/bork--git
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at 5d64e24 Add run ID to borkbot branch name, just in case
Error: inreplace failed
types/cask.sh:
  expected replacement of "/usr/local/" with #<Pathname:/usr/local>

Do not report this issue to Homebrew/brew or Homebrew/core!

bork's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

(I'm running the latest version from `main` in a different way though, so it's fine in my case)

**Comment by skylarmacdonald** [comment]
I think that's about what I did for v0.13.0 as well 😂 But I'm not against doing that again. A lot has gone into what will become 0.14.0, and the outstanding items will probably require some more in-depth reworking of the Bork core code.

Let me triage some of the new issues in the list and see if it is worth trying to include them in 0.14, or if they will need to wait as well, and if so I shall move some things around.

**Comment by lucymhdavies** [comment]
🙂

**Comment by skylarmacdonald** [comment]
[Wish granted.](https://github.com/borksh/bork/releases/tag/v0.14.0)
